[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.23"
optimizer = true
optimizer-runs = 1000


[rpc_endpoints]
zkkatana = "https://rpc.startale.com/zkatana"


[invariant]
runs = 2000
depth = 25
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true